### ISSUE TITLE
[Italian Terminology] How to translate "account"

### ISSUE THREAD

**Issue by hrumag** [monero-ecosystem/monero-translations#30]
Hi all,

During a translation, I realized the English-Italian translation table lacks the term "account".
Now, IMHO in Italian the term "account" can be translated in two ways, depending on the context in which the term is used:

1) In general terms (e.g. internet, websites, ...) it can be left as "account". Example: "Account Facebook", "Account Gmail". That is the exact denomination.
2) In financial terminology the term has to be translated as "conto". Example: "Bank account" is "Conto bancario", not "Account bancario".

For this reason, I propose to validate the translation "Account" => "Conto" where it is meant to indicate a "repository where transactions occur", however giving the possibility to keep "account" where a less specific "authentication set (username/password)" is addressed.

**Comment by erciccione** [comment]
I would honestly prefer to leave it as 'account', this specifically to avoid the connections with bank system's terminology. At the end, a Monero account is both a 'Conto' and an 'account', since it can do much more than store money (for example, sign a message, validate a transaction etc.).

@Shrikez1 @serhack @lancillotto @faudi

Opinions on this?

**Comment by hrumag** [comment]
Good. Majorty wins. So please @erciccione add the entry on the Translation Table so keep track. Of, if it's more comfortable to you, I can open a pull request. Let me know.

**Comment by erciccione** [comment]
@hrumag Feel free to open a PR with the changes :)

**Comment by erciccione** [comment]
Resolved
