### ISSUE TITLE
[Italian Terminology] Translation of "subaddress"

### ISSUE THREAD

**Issue by hrumag** [monero-ecosystem/monero-translations#32]
The translation table indicates "sottoindirizzo", where "indirizzo" is used to translate the term "address".
How shall we move on it?

**Comment by serhack** [comment]
The term subaddress is interesting for Italian language. Definitely I think we should not use "sottoindirizzo". Leaving "subaddress" is a good idea.

**Comment by erciccione** [comment]
Actually. I just checked on [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?&searchTerm=subaddress&langID=Italian&Source=true&productid=All%20Products) and on [Linguee](https://www.linguee.com/english-italian/search?query=subaddress) and looks like 'sottoindirizzo' is widely utilized across projects. My fear was that a final user could have been confused by a new term, but i stand corrected.

So, i'm ok with the use of 'Sottoindirizzo', since, as said, is widely utilized

**Comment by hrumag** [comment]
@serhack do you agree? In case I can "revert the revert" of the PR is currently opened.

**Comment by hrumag** [comment]
@erciccione Italian terminology file does not need a PR since it is already synchronized with our decision.
