### ISSUE TITLE
German terminology: Die/Das/Der ?

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#46]
Recently, a translator raised a concern about the use of `Das wallet` in our German terminology. Monerujo uses `Das wallet` while the GUI uses `Die wallet`. This unconsistency is annoying and negatively affects UX.

We need to use one single version. There is no consensus on which form to use anfd @leza89 strongly opposes to the use of *Das*. I, instead, would prefer it because gender neutral (in our guidelines is written that gender neutral terms are preferred) and according to linguist to be i contacted, also more correct.

One of the proposals to resolve the issue is to have 2 different translations: German, which would use `Die wallet` and Austrian, which would use `Das wallet`. I'm fine with adding an Austrian translation, i'm not if the only reason is that this a translator refuses to use any other terminolgy than the one they prefer.

Since this discussion degenerated and ended up with me being insulted and accused of not listening to translators (accusation that any memeber of the localization workgroup can analize by themselves), i'm going to take the lead here and contact linguists and communities of German translators, In the meantime, anyone is free to discuss which terminology they prefer to use and why. Feel free to gain consensus for one version of the other and participate to the discussion.

The point is that we won't have a language translated in two different ways. If there is no consensus on which term to use, i will make the final decision.

This issue will be used to track progresses and the final decision.

(pinging @m2049r for knowledge)

**Comment by Keksoj** [comment]
As a non-native but fluent german speaker, I find `Die Wallet` to be more fluid, more *natural* and I have no real rational justification for it. 
I disagree about this gender neutrality idea. Unfortunately, there is NO consensus in german about which article to use for foreign words. There might be some well-intended language specialists to propose rules, but the crowd NEVER follows them. For instance, an app is `die App` in german, for no reason.

Having a different article for a german and an austrian version would be preposterous, in my opinion.
Having the same article for both the GUI and the App would be great, whichever it is.
I'd rather have `das Wallet` than a resurgence of the conflict we saw, or than a splitting of german/austrian versions.

**Comment by rodolfo912** [comment]
@erciccione 

> Monerujo uses `Das wallet` while the GUI uses `Die wallet`.

Monerujo is inconsistent at the moment. Mostly `das` is used but there are also cases of `die`.

I agree with @Keksoj and am also in favor of `die Wallet` because my *Sprachgefühl* (hah, this is also an English word :) says so. `Das Wallet` sounds odd to me.

I can only repeat what I wrote on IRC, this is not an issue of gender neutrality (a concept, I am generally highly critical of). There is a difference in German between the grammatical and the natural gender. A wallet, obviously, does not have a natural gender but it could well have a grammatical one, like: "die Tür" (the door) or "der Stuhl" (the chair). So, the decision here should not be based on gender neutrality.

An Austrian version would probably be overkill. There should not be that much difference to a German version to justify this and it would be very unusual to have different versions of "German" (which makes me, a friend of localism, like it in a way ...).

In general, this is not an issue I will fight over.

**Comment by erciccione** [comment]
The consensus between translators is clearly to use to use `Die wallet`.

@rodolfo912 is right, Monerujo uses different ways to do it. @m2049r would you consider change your mind and adapt Monerujo's terminology according to this consensus? It would save some more drama, i think we spent way too much time and health arguing on a word :).

**Comment by m2049r** [comment]
I agree that we are spending a lot of time and health on one word. On the other hand, it goes to show that it may be an important one.

If we look at the way it is used in the wild, we see [heise using 'das Wallet'](https://www.heise.de/ct/artikel/So-funktioniert-die-Kryptowaehrung-Bitcoin-3742304.html), [chip using 'die Wallet' in the written text but 'das Wallet' in the attached video](https://praxistipps.chip.de/bitcoin-wallet-was-ist-das_39912) and [Süddeutsch Zeitung using 'das Wallet'](https://www.sueddeutsche.de/wirtschaft/kryptowaehrungen-der-lange-weg-vom-bitcoin-zum-euro-1.3828930). Other publications use 'das' and 'die' at random.

Considering heise and Süddeutsche Zeitung to be serious publications, I propose to use 'das' for the whole Monero ecosystem - not just for Monerujo.

I would also like to add, that the current inconsistency in the Monerujo translation is not an argument for anything as it has been introduced by translators themselves, indicating there is no consensus.

**Comment by erciccione** [comment]
>  I propose to use 'das' for the whole Monero ecosystem - not just for Monerujo.

Whatever term will be chosen on this issue will be used for the entire ecosystem.

Pinging recent german translator who worked on monerujo: @wobole. more opinions we have, the better

**Comment by Wobole** [comment]
Since there are several words which would be translated as wallet ("die Geldbörse" (f), "der Geldbeutel" (m), "das Portemonnaie" (n)), this is actually a hard decision, and the discussion on this would very probably not be solved though adding an Austrian translation (I agree with @Keksoj  and @rodolfo912  at this point). Btw, I guess `die App` refers to "die Anwendung" or "die Applikation", but seems like the Germans somehow dice their articles, true.

Basically, I would agree with @m2049r as to choose `das wallet`.  
In my understanding, a use of `das wallet` feels much more fluent (as far as my _Sprachgefühl_ tells me). But as this is probably not really a matter of the hunch or rather feeling of an individual, I would intuitionally have a look at other German nouns which end with the same sound: since the _'e'_ in `wallet` is a short vowel and, concerning the German language, you can roughly state that there should be a double consonant at the end of the word to "make the respective vowel a short one", we would look at words which are phonetically pronounciated like `wallet` but spelled with an additional _-t_, such as `Ballett`, `Skelett`, `Korsett`, `Amulett`, which are neutral (so you use "das [...]"). I have no idea if this makes any sense to a person who doesn't command this language, but at least I hope it does for the German-speaking community. This may be a very modest and/or naive approach, but the best I could do for now.

**Comment by erciccione** [comment]
Thanks for chipping in @Wobole 

Pinging recent German contributors from GUI: @leonklingele @rafficer @lovvskillz @Re-Diculous

**Comment by leonklingele** [comment]
[Wikipedia says](https://de.wikipedia.org/wiki/Cyberwallet):

```
Ein Cyberwallet (Alternativbezeichnungen: E-Wallet oder Digital Wallet) ermöglicht es
Nutzern, Guthaben auf elektronischen Plattformen zu speichern und zur Zahlungen für
Waren und Dienstleistungen im Internet zu nutzen.
```

`Ein Cyberwallet` means it is either `der Wallet` or `das Wallet` (but not `die Wallet`, you'd have to use `eine` instead).
I disagree about `der Wallet` which makes it a `das Wallet` (sounds much better IMO).

**Comment by ordtrogen** [comment]
The MyMonero localization over at Crowdin (https://crowdin.com/project/mymonero-app-ios) uses "Geldbörse" in German, and to an outsider like me, it sounds odd to use an English word (wallet).

![image](https://user-images.githubusercontent.com/15184875/55688915-a88bdb00-597e-11e9-9dd6-d754a72dd3bc.png)

**Comment by ordtrogen** [comment]
I had a quick look at the Bitcoin client localization and German seems to mix "Brieftasche" and "Wallet"
(I haven't followed you previous discussion so maybe this has already been pointed out)

**Comment by Leza89** [comment]
## Pro and contra according to language rules

> `wallet` but spelled with an additional _-t_, such as `Ballett`, `Skelett`, `Korsett`, `Amulett`, which are neutral (so you use "das [...]").

This has been the best argument for das Wallet I came across when I was looking into this topic myself – however I was not really pleased with it because the suffix is different (in writing and pronounciation) for the mentioned examples from "wallet" (Try it out and pronounce "Wallet" like "Ballett" - it sounds wrong).

The Counterargument would be to use the method of the translated word in german which – as has been pointed out – is a bit tricky because there is every possible article. However "Brieftasche" and "Geldbörse" are the most common.

## Sprachgefühl

Besides the "language laws" there is the aforementioned "Sprachgefühl" which gives an inherent sense of the article to be used for people fluent in german; Additionally, this also gives a sense of disorientation, if the expected article doesn't match the used one.

## A case for a seperate localization

Please take into consideration that this "Sprachgefühl" differs – especially from north to sourth – and both "die" and "das" are correct on their own terms. Splitting de into 

* de/de (language code: de) - Deutsch(Deutschland)
* de/at (language code: at) - Deutsch (Österreich)

would give both preferences a version they feel comfortable with. Also please keep in mind that we also had discussions with e.g. @leonklingele about "der Node" or "das Node" of which I think the cause is rooted in a similar area. I'd also like to point your attention to different terminology that exists within these "two" languages: https://de.wikipedia.org/wiki/Liste_von_Austriazismen

## Pro and contra in relation to other projects and publications

Another counterargument would be that the majority of projects known to me use "die Wallet" already and there has been a discussion and a poll on this topic 6 years ago:

https://bitcointalk.org/index.php?topic=228313.0

What I've found so far (Additonally to previous mentions) is that:

Usage of

"die Wallet": [Bitcoin](https://bitcoin.org/de/waehlen-sie-ihre-wallet), [Bitcoin Cash (https://www.bitcoincash.org/de/), [Bitcoinblog.de(popular german crypto blog)](https://bitcoinblog.de/2014/03/05/wallets-im-vergleich/)
"das Wallet": [Litecoin](https://litecoin.org/de/), [Coinwelt.de - Ethereum Tutorial](https://www.coinwelt.de/2016/02/ethereum-wallet-anleitung-und-informationen/)

## Addendum

I wanted to add that I will accept a consensus if it is reached (at the current moment I think that two translations would be the best option possible for everyone involved), but I will not contribute my (unpaid, voluntary) time to the exhaustive task of changing almost all of Monero's translations from "die Wallet" to "das Wallet".

**Comment by Rafficer** [comment]
I didn't read the whole thread, but "das Wallet" just sounds a lot more natural to me. "die Wallet" just sounds plain awful imo.

**Comment by erciccione** [comment]
I am happy to see so much participation on this issue. I'm gonna leave it open for a couple more days for further comments then we will decide according to the consensus (which seems quite clear at the moment).

**Comment by Leza89** [comment]
I'm counting 4 for "das" and 4 for "die"

**Comment by lovvskillz** [comment]
I personally prefer `die Wallet` because it sounds better or more natural to me.

**Comment by erciccione** [comment]
The consensus is basically even, i asked for some feedback on the /r/german community on reddit: https://www.reddit.com/r/German/comments/bcfewf/das_wallet_or_die_wallet/

Hope some of them will comment here. Right now we have no strong support for one term above the other and most of the reasons from both sides are about "how it sounds". If this is the case and there are no strong grammatical reasons for one way or another, we ill go for **Das wallet**, i don't think would be wise/useful to have two languages on Monerujo *because of one single word* and i'm not going to force @m2049r to use a terminology he doesn't like on his app, especially since some supporters of *Die wallet* declared they don't care much about the issue.

**Comment by rbrunner7** [comment]
I am not sure I remember correctly, but isn't there a "loosely followed convention" in such cases that the English word gets the same article as the corresponding German word (which is avoided because not "cool", too long, not known enough, whatever) would get?

Example: If *wallet* is used in German as a loan word to replace *Geldbörse*, because it's **die** Geldbörse there would be a tendency to use **die** Wallet.

On the other hand, I just read @Rafficer 's comment that different words for that "thing" to carry money around are in use in different regions in Germany, all with a different article, so ...

On the third hand, a quick Google test: "die Wallet" (with quotes as part of the search term, to look out for places where those two words occur together) gives me around 160'000 hits, "das Wallet" only 40'000, and finally "der Wallet" 35'000.

My own (native speaker) gut feeling leans towards "die Wallet", but not very strongly. "das Wallet" would also fly.

**Comment by Leza89** [comment]
and finally "der Wallet" 35'000.

I'd imagine that these are cases like "Passwort der Wallet" (usage of "die") – for "das Wallet" it would be "Passwort des Wallets"

**Comment by erciccione** [comment]
The poll on reddit was unconclusive and consensus is still divided. There are no strong technical reasons to choose a term instead of the other one. I confirm what i anticipated in my last message: we will use `Das Wallet` for all German translations from now on.

If you feel there are reasons to open another discussion about this term, please open another issue referencing to this one.
#45 Will need to be changed accorgingly.

Thanks to everyone who participated to the discussion, here or on reddit.

**Comment by erciccione** [comment]
Could somebody review #46 pls?
