### ISSUE TITLE
Comments on Spanish terminology

### ISSUE THREAD

**Issue by ordtrogen** [monero-ecosystem/monero-translations#9]
@BlackLotus64 @lh1008 et al

Just some brief notes as I was looking thru it:

> Stagenet | Fase de la red | Para discusión. Dejarla como está o traducirla

The main part of "stagenet" is "net" so a "stagenet" is a type of "net"' but your suggestion "fase de la red" has "fase" as its main part which wouldn't be correct (fase = stage). I think there are three "nets" in Monero: testnet (for testing), stagenet (for "staging" i.e "preparation for production") and mainnet (the actual live network and corresponding blockchain). 

For Swedish, I'm considering leaving all three untranslated as if they were names. Just like we don't translate internet in the different languages

> Wallet | Monedero | Se tomó "monedero" porque ya está siendo utilizado en la comunidad de Bitcoin

It appears that "cartera" is pretty common, too. But I remember at some point suggesting "monedero" because it's synomous with "cartera" and is a word that is similar in appearance to "monero". Sound cool to say "tengo monero en mi monedero". So I like the translation but maybe the motivation should be updated to say something about its likeness to "monero" (maybe you've discussed this elsewhere that I've missed)

> ## Not translated

"blob" is an acronym for Binary Large Object and Microsoft Terminology database just lists it as "blob", so maybe that's it.

"nounce" - I'm pretty sure that you mean "nonce", which is a small value a mining software adds to a block when trying to solve it. Unfortunately I have no suggestion for a translation.

**Comment by lh1008** [comment]
Hey @ordtrogen,

What have other translators spoken about these 3 words (testnet, mainnet, stagenet)?

About the word "monedero", sure most of the contributors agreed in what you said, "it sounds cool to say 'tengo monero en mi monedero' " (I was one of them), and we also agreed on using "monedero" in the same terms [bitcoin-monedero](https://bitcoin.org/es/vocabulario#monedero) agreed on using this word translation. 

For "blob" and "nounce" I agree on what you say, those words are better to leave them as they are. Maybe if someone asks about the definition we could work out a translation for "blob" as "objeto binario grande/largo" but keep the acronym 

Thank you :).

**Comment by lh1008** [comment]
@ordtrogen I will open a discussion about this type of words so we can work together to choose which words not to translate and we could all agree upon in the #monero-translations channel. :)

**Comment by BlackLotus64** [comment]
Yes, that's what I meant, it's better to discuss them with other users.

BTW I was going to comment but my pc crashed haha. For stagenet, I can add that it could be something like _red de producción_ or _red de procesos_ given its meaning, as testnet is _red de pruebas_ and mainnet _red principal_.

We can use this or another discussion for just terminology. I'm not sure if it's a good idea to open various discussions for every time a word or words need to be discussed.

**Comment by lh1008** [comment]
@ordtrogen what about "Red de Fase"?

I was not sure about the "stagenet" definition. I worked with the word "fase" because it still means a stage before in time. It's preparing for something.

I don't have any knowledge about swedish so it's hard for me to give you a comment about any translation in that language.

I was thinking about something, if we have a definition of "testnet" meaning "Red de prueba" (there is no other definition, and is a clear definition and translation); or for "mainnet" - "Red principal" and we work with them, we should also try and figure out how to work with other similar definitions such as "stagenet".

I would like to share you from a discussion (in the telegram chat room @MoneroEsp) with other guys about other-like definitions e.g. "Hash rate", "hashing power". There is no clear definition of the word ["hash"](https://techterms.com/definition/hash) from English to Spanish, like the word "Internet",  but if we look at the Bitcoin community the words ["hash rate"](https://bitcoin.org/en/vocabulary#hash-rate), has a meaning, "the measuring unit of the processing power of the Bitcoin network", so **"hashing power"**, by "default" should mean "poder de procesamiento", and not "poder de hash". This is an example of finding the correct words and translation for the tech words used in the cryptocurrency technology. I contributor also suggested to work as hard as we could to find definitions to words that have translations in our especific language (spanish, french, russian, chinese, portuguese, could be any language, etc.) because if we dismissed those words we could attack harshly the vocabulary in any particular language, and make it harder for new users to adapt to the definitions. We sure understand there are some words, like "Internet", "hash", "pool", "deamon", "bit", "stealth address", etc. that are some of those words with hardly any translation at all. But we encourage the word finding for each definition/translation as a priority.

**Comment by lh1008** [comment]
"Red de producción" +1

@BlackLotus64 we could work on one open discussion of the terminology and from there open issues for any type of word or words, and when the discussion is over close it and "merge" changes. Is this possible?

**Comment by ordtrogen** [comment]
>For "blob" and "nounce" I agree on what you say

Sure. Note that I'm pretty sure it's "nonce" and not "nounce" so you may want to correct that in the spanish terminology page

>What have other translators spoken about these 3 words (testnet, mainnet, stagenet)?

I haven't checked the other translations. In fact I can't remember if I've come across them yet when translating to Swedish.

>@ordtrogen what about "Red de Fase"?

My tech Spanish isn't strong enough to have an opinion. Just had this thought that just like we don't translate "internet" in different languages, e.g you don't say "red de redes" or something in Spanish, even though that's more or less why it's called the internet, you could look at mainnet etc as just names and leave them untranslated.

But probably the best first step would be instead to create good entries in Moneropedia that describe these nets. That would both be useful and help the discussion of whether to translate or not.

>so "hashing power", by "default" should mean "poder de procesamiento", and not "poder de hash". 

Not sure I agree. "Hashing power" is pretty specific whereas "processing power" (poder de procesamiento) is general. The key term is the "hashing function", which is a specific function, in Bitcoin's case sha256, and the hashing power of the bitcoin network is the number of times the miners can call the hashing function per second. That's why it's measured in hashes per second. And today it's in the Tera-hashes per sec (Th/s). So it's a _type of_ processing power, but it specific in that it only refers to calls to the hashing function. 
When I read that https://bitcoin.org/en/vocabulary#hash-rate  I don't think it's very well explained. Look at the term "hash rate" where "rate" could be "tasa", like in "tasa de bits"

Should probably be a topic in Moneropedia as well

**Comment by lh1008** [comment]
Yeah, I still kept on writing "nounce" is "nonce". 

In the other hand what I just thought is that we need to assess that each time a user will find these words, they will always look for its definition and in that case its translation. Even if we keep the name in English, they will always ask, "hey, what's 'stagenet, mainnet, or testnet'?", and the surprise about this is that they will find the translation and then they will process this information as it is. They will say, "oh yes, it's "red de pruebas, red de producción, red principal". So we have to think the easiest way for them to process this information in their own language and the way they will process it, instead of trying to impose a "new" type of language, having the words to translate them. There are literally some words that will still be really difficult to understand or translate even if we have the words to translate them, and the example is "hash". A "hash = función" but "función" does not give a direct translation or give a direct idea on what it refers what miners calls mean in the network. So we can't translate hash even if we could have the words to, like Internet, "red interna; red de redes". The "hashing power", "poder de procesamiento" gives a more clear idea that if you have "processing power" most likely you will have "hashing power". There are even some translation that will need the "poder de hash" translation a necesity to make clear what mining stands for. So we have to consider when will be appropiate to use "poder de procesamiento" and when to use "poder de hash/es".

In the #monero-translations channel we spoke about these terms and we have to consider several aspects about this:
1. Cryptocurreny regional knowledge.
2. Research what type of terminologies are already being used in the space and the region's language.
3. If there is no previous reference in the words we should discuss what will make sense to the people who will read the text.

**Comment by lh1008** [comment]
#42 
Stagenet still has not yet been defined. Open for discussion.
